name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17']
    name: Run Tests (Java ${{ matrix.java }})
    steps:
    - name: Checkout
      uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
    - uses: guardian/setup-scala@v1
    - name: Build and Test
      run: sbt +clean +compile +test
