name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian
      SKIP_NODE: true
      EXCLUDE: atom-manager-play-lib,atom-publisher-lib
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
